## basic info
site_name: "1Panel Documentation"
site_url: "https://1panel.hk"
site_description: "1Panel Top-Rated Web-based Linux Server Management Tool"
repo_name: "1Panel"
repo_url: "https://github.com/1Panel-dev/1Panel"
edit_uri: https://github.com/1Panel-dev/docs/edit/i18n/docs/
copyright: Copyright &copy; 2024 Lingxia (Hong Kong) Software Co., Limited, All Rights Reserved.

## customization
theme:
  name: "material"
  logo: "img/logo-white.png"
  favicon: "img/facio.ico"
  language: "en"
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top

  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - toc:
      permalink: true
  ## admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  ## content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ## grid
  - attr_list
  - md_in_html      
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version:
    method: mike

## content nav
nav:
  - Introdoction: index.md
  - Installation: installation.md
  - User Manual:
      - App Store:
          - Summary: user_manual/appstore/appstore.md
          - Install Application: user_manual/appstore/install.md
          - App Operations: user_manual/appstore/operations.md
      - Website:
          - Websites:
              - Summary: user_manual/websites/websites.md
              - Create a Website: user_manual/websites/website_create.md
              - Basic Settings: user_manual/websites/website_config_basic.md
              - Website Logs: user_manual/websites/website_logs.md
              - Additional Settings: user_manual/websites/website_config_additional.md
              - Website Group: user_manual/websites/website_group.md
              - Backup and Restore: user_manual/websites/website_backup.md
              - Delete a Website: user_manual/websites/website_delete.md
              - OpenResty Operations: user_manual/websites/openresty.md
          - SSL Certificate:
              - Summary: user_manual/websites/certificate.md
              - Request a Certificate: user_manual/websites/certificate_request.md
              - ACME Account: user_manual/websites/certificate_acme.md
              - DNS Provider: user_manual/websites/certificate_dns.md
          - Runtime:
              - PHP: user_manual/websites/runtime_php.md
            #   - Node.js: user_manual/websites/runtime_node.md
            #   - Java: user_manual/websites/runtime_java.md
            #   - Golang: user_manual/websites/runtime_golang.md
            #   - Python: user_manual/websites/runtime_python.md
      - Databases:
          - MySQL and MariaDB: user_manual/databases/mysql.md
          - PostgreSQL: user_manual/databases/postgresql.md
          - Redis: user_manual/databases/redis.md
      - Containers:
          - Introduction: user_manual/containers/introduction.md
          - Containers: user_manual/containers/containers.md
          - Composes: user_manual/containers/composes.md
          - Images: user_manual/containers/images.md
          - Networks: user_manual/containers/networks.md
          - Volumes: user_manual/containers/volumes.md
        #   - Comtainer Registries : user_manual/containers/registries.md
        #   - Compose Templates: user_manual/containers/compose_templates.md
        #   - Settings: user_manual/containers/settings.md
      - Cron Jobs: user_manual/cronjobs.md
    #   - Host:
    #       - File: user_manual/hosts/file.md
    #       - Monitor: user_manual/hosts/monitor.md
    #       - Terminal: user_manual/hosts/terminal.md
    #       - Firewall: user_manual/hosts/firewall.md
    #       - Process: user_manual/hosts/process.md
    #       - SSH Setting: user_manual/hosts/ssh.md
      - Toolbox:
          - Quick Setup: user_manual/toolbox/quick_settings.md
          - Cache clean: user_manual/toolbox/clean.md
        #   - Supervisor: user_manual/toolbox/supervisor.md
          - Virus Scan: user_manual/toolbox/clam.md
          - FTP: user_manual/toolbox/ftp.md
        #   - Fail2ban: user_manual/toolbox/fail2ban.md
    #   - Logs: user_manual/logs.md
    #   - Settings: user_manual/settings.md
#   - Tutorials: tutorials.md