site_name: '1Panel 文档'
site_url: 'https://1panel.cn/docs'
site_author: '飞致云'
site_description: "1Panel 在线使用文档"

repo_name: '1Panel-dev/1Panel'
repo_url: 'https://github.com/1Panel-dev/1Panel'
edit_uri: ''

theme:
  name: 'material'
  logo: 'img/logo-white.png'
  favicon: 'img/facio.ico'
  language: 'zh'
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  custom_dir: 'theme'
  icon:
    repo: fontawesome/brands/github

nav:
  - 产品介绍: index.md
  - 安装部署:
    - 在线安装: installation/online_installation.md
    - 在线升级: installation/online_upgrade.md
    - 1Panel 离线版: installation/package_installation.md
    - 阿里云镜像部署: installation/ali_cloud.md
    - 从 V1 版本升级:
      - 升级说明: installation/v1_migrate.md
      - 操作步骤: installation/v1_migrate_steps.md
    - 主从节点切换: installation/master_migrate.md
    - 命令行工具: installation/cli.md
  - 功能手册:
    - 应用商店:
      - 概述: user_manual/appstore/appstore.md
      - 安装部署: user_manual/appstore/install.md
      - 应用操作: user_manual/appstore/installed.md
      - 应用商店设置: user_manual/appstore/setting.md
    - AI:
      - 智能体: https://openclaw.club/archives/9u1xZTMF
      - 模型: 
        - Ollama: user_manual/ai/model.md
        - vLLM: user_manual/ai/vllm.md
      - AI 网关: user_manual/ai/gateway.md
      - 基准测试: user_manual/ai/benchmark.md
      - MCP: user_manual/ai/mcp.md
      - GPU 监控: user_manual/ai/gpu.md
    - 网站:
      - 概述: user_manual/websites/websites.md
      - 创建网站: user_manual/websites/website_create.md
      - 基本设置: user_manual/websites/website_config_basic.md
      - 其他设置: user_manual/websites/website_config_other.md
      - 网站分组: user_manual/websites/website_group.md
      - 网站备份: user_manual/websites/website_backup.md
      - OpenResty 设置: user_manual/websites/openresty.md
    - 证书:
      - 证书概述: user_manual/websites/certificate.md
      - 申请证书: user_manual/websites/certificate_create.md
      - 上传证书: user_manual/websites/certificate_upload.md
      - 自签证书: user_manual/websites/certificate_self_sign.md
      - 续签证书: user_manual/websites/certificate_renew.md
      - Acme 账户: user_manual/websites/certificate_acme.md
      - DNS 账户: user_manual/websites/certificate_dns.md
    - 运行环境:
      - PHP: user_manual/websites/php.md
      - Node.js: user_manual/websites/node.md
      - Java: user_manual/websites/java.md
      - Golang: user_manual/websites/golang.md
      - Python: user_manual/websites/python.md
      - .NET: user_manual/websites/dotnet.md
    - 数据库:
      - MySQL: user_manual/databases/mysql.md
      - PostgreSQL: user_manual/databases/postgresql.md
      - Redis: user_manual/databases/redis.md
    - 容器:
      - 概览: user_manual/containers/overview.md
      - 容器: user_manual/containers/container.md
      - 编排: user_manual/containers/compose.md
      - 镜像: user_manual/containers/image.md
      - 网络: user_manual/containers/network.md
      - 存储卷: user_manual/containers/volume.md
      - 仓库: user_manual/containers/repo.md
      - 编排模版: user_manual/containers/compose_template.md
      - 配置: user_manual/containers/setting.md
    - 系统:
      - 文件: user_manual/hosts/file.md
      - 监控: user_manual/hosts/monitor.md
      - 防火墙: user_manual/hosts/firewall.md
      - 进程管理: user_manual/hosts/process.md
      - SSH 管理: user_manual/hosts/ssh.md
    - 终端: user_manual/terminal.md
    - 计划任务: user_manual/cronjobs.md
    - 工具箱:
      - 快速设置: user_manual/toolbox/quick_settings.md
      - 缓存清理: user_manual/toolbox/clean.md
      - 进程守护: user_manual/toolbox/supervisor.md
      - 病毒扫描: user_manual/toolbox/clam.md
      - FTP: user_manual/toolbox/ftp.md
      - Fail2ban: user_manual/toolbox/fail2ban.md
    - 高级功能:
      - WAF:
        - 概述: user_manual/xpack/waf/waf.md
        - 概览: user_manual/xpack/waf/dashboard.md
        - 全局设置: user_manual/xpack/waf/global.md
        - 网站设置: user_manual/xpack/waf/site.md
        - 拦截记录: user_manual/xpack/waf/log.md
        - 封锁记录: user_manual/xpack/waf/block.md
      - 💎节点管理: user_manual/xpack/node.md
      - 💎网站防篡改: user_manual/xpack/tamper.md
    - 日志审计: user_manual/logs.md
    - 面板设置: user_manual/settings.md
  - 常用软件:
    - OpenClaw: user_manual/appstore/openclaw.md
    - Hermes Agent: user_manual/appstore/hermes-agent.md
    - OpenResty: user_manual/appstore/openresty.md
    - MySQL: user_manual/appstore/mysql.md
    - Redis: user_manual/appstore/redis.md
    - Ollama: user_manual/appstore/ollama.md
    - Halo: user_manual/appstore/halo.md
    - OpenList: user_manual/appstore/openlist.md
    - MaxKB: user_manual/appstore/maxkb.md
    - phpMyAdmin: user_manual/appstore/phpmyadmin.md
    - WordPress: user_manual/appstore/wordpress.md
    - Zabbix: user_manual/appstore/zabbix.md
    - AList: user_manual/appstore/alist.md
    - frp: user_manual/appstore/frp.md
    - 青龙: user_manual/appstore/qinglong.md
    - Nginx Proxy Manager: user_manual/appstore/nginx-proxy-manager.md
    - ddns-go: user_manual/appstore/ddns-go.md
    - Gitea: user_manual/appstore/gitea.md
    - DataEase: user_manual/appstore/dataease.md
    - Open WebUI: user_manual/appstore/openwebui.md
    - MariaDB: user_manual/appstore/mariadb.md
    - RustDesk: user_manual/appstore/rustdesk.md
    - MinIO: user_manual/appstore/minio.md
    - Bitwarden: user_manual/appstore/bitwarden.md
    - Home Assistant: user_manual/appstore/home-assistant.md
    - MongoDB: user_manual/appstore/mongodb.md
    - Nextcloud: user_manual/appstore/nextcloud.md
    - LobeChat: user_manual/appstore/lobechat.md
    - Jumpserver: user_manual/appstore/jumpserver.md
    - Stirling-PDF: user_manual/appstore/stirling-pdf.md
    - ChatGPT-Next-Web: user_manual/appstore/chatgpt-next-web.md
    - Cloudreve: user_manual/appstore/cloudreve.md
    - Uptime Kuma: user_manual/appstore/uptime-kuma.md
    - VS Code: user_manual/appstore/vscode.md
  - 常见问题:
    - 产品 FAQ: faq/faq.md
    - 操作系统相关: faq/operating_system.md
    - 系统功能相关: faq/system_function.md
    - 服务器架构相关: faq/server_architecture.md
    - OpenClaw 相关: faq/openclaw.md
  - API 接口: dev_manual/api_manual.md
  - Skills 技能: dev_manual/skills.md
  - 版本迭代: changelog.md
  - 联系我们: contact.md
  - 商业版本:
    - 1Panel 企业版: https://1panel.cn/enterprise.html
    - 1Panel 专业版: https://www.lxware.cn/1panel
    - 版本功能对比: https://1panel.cn/versions.html
  - 1Panel AI 一体机:
    - AI 助理一体机（GB10版）: https://1panel.cn/openclaw.html
    - AI 编程一体机（GB10版）: https://1panel.cn/aicoding_gb10.html
    - AI 编程一体机（B70版）: https://1panel.cn/aicoding_b70.html

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  1Panel:
    tag: v1.10.29
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
    boost: 100
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-P2ER2N0NSN
  social:
    - icon: Bilibili_Logo_Blue
      link: https://space.bilibili.com/510493147/lists/1199760
    - icon: fontawesome/brands/github
      link: https://github.com/1Panel-dev
    - icon: fontawesome/solid/envelope
      link: mailto:wanghe@fit2cloud.com
    - icon: fontawesome/brands/skype
      link: tel://400-052-0755

extra_css:
  - css/extra.css
  - css/termynal.css
  - css/custom.css
  - stylesheets/extra.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

copyright: Copyright &copy; 2014-2026 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">浙ICP备14038283号-5</a>

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+'
  - macros
