## basic info
site_name: "1Panel Documentation"
site_url: "https://docs.1panel.pro"
site_description: "1Panel Open-source Linux Server Operation & Management Panel"
site_author: "1Panel"
repo_name: "1Panel"
repo_url: "https://github.com/1Panel-dev/1Panel"
edit_uri: https://github.com/1Panel-dev/docs/edit/i18n/docs/
copyright: Copyright &copy; 2025 Lingxia (Hong Kong) Software Co., Limited, All Rights Reserved.

## customization
theme:
  name: "material"
  logo: "img/logo-white.png"
  favicon: "img/facio.ico"
  language: "en"
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: "theme"
  icon:
    repo: fontawesome/brands/github

## content nav
nav:
  - Overview: index.md
  - Installation:
    - Online Install: installation/online_installation.md
    - Online Upgrade: installation/online_upgrade.md
    - 1Panel Offline Edition: installation/package_installation.md
    - Alibaba Cloud Image: installation/ali_cloud.md
    - Upgrade from V1:
      - Upgrade Notes: installation/v1_migrate.md
      - Steps: installation/v1_migrate_steps.md
    - Master-Slave Switch: installation/master_migrate.md
    - CLI Tool: installation/cli.md
  - User Manual:
    - App Store:
      - Overview: user_manual/appstore/appstore.md
      - Install: user_manual/appstore/install.md
      - App Operations: user_manual/appstore/installed.md
      - App Store Settings: user_manual/appstore/setting.md
    - AI:
      - Agent: user_manual/ai/agent.md
      - Model: user_manual/ai/model.md
      - MCP: user_manual/ai/mcp.md
      - GPU Monitor: user_manual/ai/gpu.md
    - Website:
      - Overview: user_manual/websites/websites.md
      - Create Website: user_manual/websites/website_create.md
      - Basic Settings: user_manual/websites/website_config_basic.md
      - Other Settings: user_manual/websites/website_config_other.md
      - Website Group: user_manual/websites/website_group.md
      - Website Backup: user_manual/websites/website_backup.md
      - OpenResty Settings: user_manual/websites/openresty.md
    - SSL Certificate:
      - Overview: user_manual/websites/certificate.md
      - Apply Certificate: user_manual/websites/certificate_create.md
      - Upload Certificate: user_manual/websites/certificate_upload.md
      - Self-signed Certificate: user_manual/websites/certificate_self_sign.md
      - Renew Certificate: user_manual/websites/certificate_renew.md
      - Acme Account: user_manual/websites/certificate_acme.md
      - DNS Account: user_manual/websites/certificate_dns.md
    - Runtime:
      - PHP: user_manual/websites/php.md
      - Node.js: user_manual/websites/node.md
      - Java: user_manual/websites/java.md
      - Golang: user_manual/websites/golang.md
      - Python: user_manual/websites/python.md
      - .NET: user_manual/websites/dotnet.md
    - Database:
      - MySQL: user_manual/databases/mysql.md
      - PostgreSQL: user_manual/databases/postgresql.md
      - Redis: user_manual/databases/redis.md
    - Container:
      - Overview: user_manual/containers/overview.md
      - Containers: user_manual/containers/container.md
      - Composes: user_manual/containers/compose.md
      - Images: user_manual/containers/image.md
      - Network: user_manual/containers/network.md
      - Volumes: user_manual/containers/volumes.md
      - Registry: user_manual/containers/repo.md
      - Compose Template: user_manual/containers/compose_template.md
      - Settings: user_manual/containers/setting.md
    - System:
      - File: user_manual/system/file.md
      - Monitor: user_manual/system/monitor.md
      - Firewall: user_manual/system/firewall.md
      - Process: user_manual/system/process.md
      - SSH Management: user_manual/system/ssh.md
    - Terminal: user_manual/terminal.md
    - Cron Jobs: user_manual/cronjobs.md
    - Toolbox:
      - Quick Settings: user_manual/toolbox/quick_settings.md
      - Clean Cache: user_manual/toolbox/clean.md
      - Supervisor: user_manual/toolbox/supervisor.md
      - Virus Scan: user_manual/toolbox/clam.md
      - FTP: user_manual/toolbox/ftp.md
      - Fail2ban: user_manual/toolbox/fail2ban.md
    - Advanced Features:
      - WAF:
        - Overview: user_manual/xpack/waf/waf.md
        - Dashboard: user_manual/xpack/waf/dashboard.md
        - Global Settings: user_manual/xpack/waf/global.md
        - Website Settings: user_manual/xpack/waf/site.md
        - Block Logs: user_manual/xpack/waf/log.md
        - Block Records: user_manual/xpack/waf/block.md
      - Node Management: user_manual/xpack/node.md
      - Website Anti-Tamper: user_manual/xpack/tamper.md
    - Log Audit: user_manual/logs.md
    - Panel Settings: user_manual/settings.md
  - Popular Apps:
    - OpenClaw: user_manual/appstore/openclaw.md
    - OpenResty: user_manual/appstore/openresty.md
    - MySQL: user_manual/appstore/mysql.md
    - Redis: user_manual/appstore/redis.md
    - Ollama: user_manual/appstore/ollama.md
    - Halo: user_manual/appstore/halo.md
    - OpenList: user_manual/appstore/openlist.md
    - MaxKB: user_manual/appstore/maxkb.md
    - phpMyAdmin: user_manual/appstore/phpmyadmin.md
    - WordPress: user_manual/appstore/wordpress.md
    - Zabbix: user_manual/appstore/zabbix.md
    - AList: user_manual/appstore/alist.md
    - frp: user_manual/appstore/frp.md
    - Qinglong: user_manual/appstore/qinglong.md
    - Nginx Proxy Manager: user_manual/appstore/nginx-proxy-manager.md
    - ddns-go: user_manual/appstore/ddns-go.md
    - Gitea: user_manual/appstore/gitea.md
    - DataEase: user_manual/appstore/dataease.md
    - Open WebUI: user_manual/appstore/openwebui.md
    - MariaDB: user_manual/appstore/mariadb.md
    - RustDesk: user_manual/appstore/rustdesk.md
    - MinIO: user_manual/appstore/minio.md
    - Bitwarden: user_manual/appstore/bitwarden.md
    - Home Assistant: user_manual/appstore/home-assistant.md
    - MongoDB: user_manual/appstore/mongodb.md
    - Nextcloud: user_manual/appstore/nextcloud.md
    - LobeChat: user_manual/appstore/lobechat.md
    - Jumpserver: user_manual/appstore/jumpserver.md
    - Moltbot: user_manual/appstore/moltbot.md
    - Stirling-PDF: user_manual/appstore/stirling-pdf.md
    - ChatGPT-Next-Web: user_manual/appstore/chatgpt-next-web.md
    - Cloudreve: user_manual/appstore/cloudreve.md
    - Uptime Kuma: user_manual/appstore/uptime-kuma.md
    - VS Code: user_manual/appstore/vscode.md
  - FAQ:
    - Product FAQ: faq/faq.md
    - OS Related: faq/operating_system.md
    - System Related: faq/system_function.md
    - Architecture Related: faq/server_architecture.md
    - OpenClaw Related: faq/openclaw.md
  - API: dev_manual/api_manual.md
  - Changelog: changelog.md
  - Contact Us: contact.md
  - Commercial:
    - 1Panel Pro: https://www.lxware.cn/1panel
    - 1Panel Offline Edition: installation/package_installation.md

markdown_extensions:
  - toc:
      permalink: true
  ## admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  ## content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ## grid
  - attr_list
  - md_in_html      
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # 保留原配置的所有扩展
  - abbr
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  1Panel:
    tag: v1.10.29
  search:
    separator: '[\s\-\.]+'
    language: 'en'
    Content-Encoding: gzip
    boost: 100
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-1QN949WS47
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1Panel-dev/1Panel
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/1panel_linux
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@1Panel-linux
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bUpUqWqdRr

extra_css:
  - stylesheets/extra.css    
  - css/extra.css
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

plugins:
  - glightbox
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+'
